#!/usr/bin/env bash
# installs nginx and configures it on the server

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
